@echo off
echo Auto-restarting LocalTunnel...
:loop
echo Starting LocalTunnel...
lt --port 8081 --subdomain loginapi123
echo Tunnel disconnected. Restarting in 5 seconds...
timeout /t 5 /nobreak > nul
goto loop
